### ISSUE TITLE
Have a selector to change music mode, (Major, minor or scale) while keeping the same grid. 

### ISSUE THREAD

**Issue by irshadshalu** [irshadshalu/music-grid#12]
Original HN Comment:

           (moron4hire): Would be awesome if it had a selector to change the mode while keeping the same grid selections.

**Comment by wcarss** [comment]
It looks from the [Tone docs](https://github.com/Tonejs/Tone.js#hello-tone) like you can call `synth.triggerAttackRelease` with named notes like "c4", "f#5", etc., which could make implementing a few common scales pretty easy, but `Music.svelte` use of the hardcoded frequency table `noteValues` and application of an interesting `Math.floor(i * 1.8)` when selecting from it, and call of `synth.set("detune", -1200);` overall make it more complex. I'm curious about the reasons for that stuff, because I feel like we'd have to remove or alter them if switching over to named notes / supporting scale transitions.

I'd be interested to do this if you agree those parts could be dropped. Another big question though, what do you imagine the scale-change UI would look like? I agree with you that the buttons are kind of at their limit. :)

**Comment by irshadshalu** [comment]
I started with notes like 'C4', etc on an array at first, but then I was trying out different things and found frequency values for notes and I sticked with something that sounded good (ofcourse the magic number 1.8 came from there which I now regret)...

> I'd be interested to do this if you agree those parts could be dropped. 

If we're doing this, we should preserve the default notes so that the existing songs made by people doesn't sound wrong (maintain backward compatibility) 
.

> Scale change UI

It should be a select input but I can't think of a place for it to go.

**Comment by irshadshalu** [comment]
> (ofcourse the magic number 1.8 came from there which I now regret)


I'm going to refactor this and convert the notes to standard format.

**Comment by irshadshalu** [comment]
The `noteValues` at the moment is as following     

	let noteValues = [
		246.94, 277.18, 311.13, 369.99,
		392.00, 415.30, 466.16, 554.37,
		587.33, 622.25, 659.26, 739.99,
		830.61, 932.33, 987.77, 1046.50,
		1108.73, 1244.51, 1479.98, 1661.22,
		1864.66, 2093.00, 2217.46, 2637.02,
		2959.96, 3322.44, 3520.00, 3729.31
	];


our loop iterates from 0 to 11, which is mapped to

        floor(0 * 1.8) = 0
        floor(11 * 1.8) = 19

and similarly,

       let indices = [0, 1, 3, 5, 7, 9, 10, 12, 14, 16, 18, 19]

so, we can replace our `noteValues` array with corresponding values in these indices which are..

        let noteValues = [246.94, 277.18, 369.99, 415.3, 554.37, 622.25, 659.26, 830.61, 987.77, 1108.73, 1479.98, 1661.22]



And get rid of the 1.8 


Then we have to find the notes corresponding for these frequency values

Using https://www.liutaiomottola.com/formulae/freqtab.htm, this becomes
       let notes = ['B4', 'C#4', 'F#4', 'G#4', 'C#5', 'D#5', 'E5', 'G#5', 'B5', 'C#6', 'F#6', 'G#6']

I tested these values and the music sounds exactly the same :)

**Comment by irshadshalu** [comment]
@wcarss Once #24  is accepted, I think you can take this issue up. 

Please preserve the original notes as default and call it classic, then we can add more modes on top of it and give it as third param in the URL?

**Comment by wcarss** [comment]
I tested [bradleybudas Magnum Opus](https://music-grid.surge.sh/#1352-1348-2568-2576-1290-1288-2565-2564-1352-1348-2568-2576-1290-1416-2565-2564-1352-1348-2568-2576-1290-1288-2565-2564-1352-1348-2568-2576-1290-1288-2565-2564-1352-1352-2704-2704-1352-1352-2704-2704-1352-1352-2704-2704-1352-1352-2704-2704-1344-1344-2688-2688-1344-1344-2688-2688-1344-1344-2688-2688-1344-1344-2688-2688-1280-1280-2560-2560-1280-1280-2560-2560-1280-1280-2560-2560-1280-1280-2560-2560-1024-1024-2048-2048-1024-1024-2048-2048-1024-1024-2048-2048-1024-1024-2048-2048-&400) from the bestof list and something doesn't sound right -- I think the bottom note is too high, just commenting as quick as possible before looking further into it

**Comment by wcarss** [comment]
yeah, I think the very first value should be B3, not B4.

**Comment by irshadshalu** [comment]
Thanks for pointing out! I fixed it in the PR.

**Comment by irshadshalu** [comment]
Fixed in #30
