### ISSUE TITLE
App freeze when we play around during playback

### ISSUE THREAD

**Issue by vibhoothiiaanand** [irshadshalu/music-grid#15]
This is being clearly reproduced multiple times at least using Safari 13

I found the exception
```js

[Error] Unhandled Promise Rejection: SecurityError: Attempt to use history.replaceState() more than 100 times per 30 seconds
	replaceState (bundle.js:14:292672)
	p (bundle.js:14:292672)
	(anonymous function) (bundle.js:14:293099)
	q (bundle.js:1:1367)
	M (bundle.js:1:1141)
	promiseReactionJob

```

So seems like this is related to this: https://github.com/irshadshalu/music-grid/blob/master/src/App.svelte#L97

At this state, the slider and animation do not work but it does play audio in the background.

Quick Workaround: Refresh the page

**Comment by irshadshalu** [comment]
Can you test now?

**Comment by vibhoothiiaanand** [comment]
I think it is more or less fixed
