### ISSUE TITLE
Play note on click

### ISSUE THREAD

**Issue by Shrinks99** [irshadshalu/music-grid#20]
Playing the note on click when adding it would make writing much easier, especially for long tunes.  This way the user doesn't have to wait for it to look around to the bit they just played to listen to how it sounds.

Also neat website!

**Comment by irshadshalu** [comment]
Thank you. This change was already done and tested (but not merged) in a branch `play_note_on_tap`


You can play around with this at http://musicgrid.irshadpi.me 

But it ends up sounding not too good and indistinguishable when there are already notes present, so I was unsure whether to add this. If enough people seems to agree we can add it.

**Comment by wcarss** [comment]
interesting! If `playCell(column)` only ran `if  (active)`, it might sound a bit nicer while clicking around and trying things

**Comment by Shrinks99** [comment]
> 
> 
> Thank you. This change was already done and tested (but not merged) in a branch `play_note_on_tap`
> 
> You can play around with this at http://musicgrid.irshadpi.me

This is very helpful for composing when paused, when the app is already playing it has less utility.

Nice!
